//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITextSearcher")]
public interface ITextSearcher
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextSearcher/GetNumberOfOccurence", ReplyAction="http://tempuri.org/ITextSearcher/GetNumberOfOccurenceResponse")]
    int GetNumberOfOccurence(string text, string searchedText);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextSearcher/GetNumberOfOccurence", ReplyAction="http://tempuri.org/ITextSearcher/GetNumberOfOccurenceResponse")]
    System.Threading.Tasks.Task<int> GetNumberOfOccurenceAsync(string text, string searchedText);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ITextSearcherChannel : ITextSearcher, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class TextSearcherClient : System.ServiceModel.ClientBase<ITextSearcher>, ITextSearcher
{
    
    public TextSearcherClient()
    {
    }
    
    public TextSearcherClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public TextSearcherClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TextSearcherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public TextSearcherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetNumberOfOccurence(string text, string searchedText)
    {
        return base.Channel.GetNumberOfOccurence(text, searchedText);
    }
    
    public System.Threading.Tasks.Task<int> GetNumberOfOccurenceAsync(string text, string searchedText)
    {
        return base.Channel.GetNumberOfOccurenceAsync(text, searchedText);
    }
}
