//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeConverter.ConsoleClient.TimeConverter
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "TimeConverter.ITimeConverterService")]
    public interface ITimeConverterService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITimeConverterService/GetDayOfWeek", ReplyAction = "http://tempuri.org/ITimeConverterService/GetDayOfWeekResponse")]
        string GetDayOfWeek(System.DateTime date);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/ITimeConverterService/GetDayOfWeek", ReplyAction = "http://tempuri.org/ITimeConverterService/GetDayOfWeekResponse")]
        System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeConverterServiceChannel : ConsoleClient.TimeConverter.ITimeConverterService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeConverterServiceClient : System.ServiceModel.ClientBase<ConsoleClient.TimeConverter.ITimeConverterService>, ConsoleClient.TimeConverter.ITimeConverterService
    {

        public TimeConverterServiceClient()
        {
        }

        public TimeConverterServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public TimeConverterServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public TimeConverterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public TimeConverterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public string GetDayOfWeek(System.DateTime date)
        {
            return base.Channel.GetDayOfWeek(date);
        }

        public System.Threading.Tasks.Task<string> GetDayOfWeekAsync(System.DateTime date)
        {
            return base.Channel.GetDayOfWeekAsync(date);
        }
    }
}
